### PR TITLE
Refactor Cohort Processing

### PR DESCRIPTION
**Pull request by Zrealshadow**
This PR's target to refactor the cohort process and solve the data continuity issue.
You can check the development in this PR.
Don't merge it

### CODE REVIEW

**Comment by Zrealshadow** [comment]
- [x] code implementation 
- [ ] doc and tutorial 
- [ ] Unit Test and Debug

**Comment by Zrealshadow** [comment]
Now, I have finished the main body of New Cohort Processing Part (which can solve the Data Continuity Issues).

In the next, I will complete the dock about the design and then start code-based testing to make sure there are no bugs.

**Comment by KimballCai** [comment]
continuous to work on the [COOL-cohort:refactor-cohort-processing](https://github.com/COOL-cohort/COOL/tree/refactor-cohort-processing) branch.

**Comment by Zrealshadow** [comment]
Complete logic body, push upstream for cooperative testing

**Pull request merged**
