### PR TITLE
test case for AvroDataLoaderConfig

### PR DESCRIPTION
**Pull request by qlinsey**
1.  update constructor of AvroDataLoaderConfig
2. add test case for AvroDataLoaderConfig

### CODE REVIEW

**Review by KimballCai — COMMENTED** [review]
@hugy718 please review the rest.

**Comment by KimballCai** [comment]
Please make sure that the path of the test file should be started with `java`.
e.g., `/src/test/com/nus/cool/extension/util/arrow/ArrowRowViewTest.java` is wrong.
It should be `/src/test/java/com/nus/cool/extension/util/arrow/ArrowRowViewTest.java` 

because maven compiling relies on this folder path.

**Comment by hugy718** [comment]
Thank you for the contribution, we have tested after fixing the path and will merge this into `dev`. In the future, please rebase with respect to the latest `dev` branch head before submitting pull requests.

**Review by hugy718 — APPROVED** [review]
LGTM. (I have ran those tests)

**Comment by qlinsey** [comment]
> Please make sure that the path of the test file should be started with `java`. e.g., `/src/test/com/nus/cool/extension/util/arrow/ArrowRowViewTest.java` is wrong. It should be `/src/test/java/com/nus/cool/extension/util/arrow/ArrowRowViewTest.java`
> 
> because maven compiling relies on this folder path.

It seems this piece of code was merged. Next time will take care of the path. Thanks.

**Comment by qlinsey** [comment]
> Thank you for the contribution, we have tested after fixing the path and will merge this into `dev`. In the future, please rebase with respect to the latest `dev` branch head before submitting pull requests.

Sure, thanks.

**Pull request merged**
