### PR TITLE
Refactor, use global_Id instead of raw value in Filter

### PR DESCRIPTION
**Pull request by Zrealshadow**

### CODE REVIEW

**Comment by Zrealshadow** [comment]
Can not pass `MetaCubeTest`.
I have modified some interface of storage layer. 
Some functions of storage layer are outdated.

**Comment by Zrealshadow** [comment]
I have modified some interface in io layer.
Maybe `CubletSave` function have to re-implement based on new interface.
Then we can pass all unit test

**Comment by KimballCai** [comment]
The code format has not been checked. Need to open another PR to format these codes.

**Comment by hugy718** [comment]
There are so many files that have no meaningful changes but with their formats reverted back to codes before formatting. I just discussed with @Zrealshadow, and the plan is to open a new branch from `dev`, so that we all have write access to it. Open a new PR from that branch to `dev`. As we review the codes, we check if the diff is mere code formatting and use the dev branch files to replace their contents. @NLGithubWP @KimballCai

**Comment by Zrealshadow** [comment]
OK, `refactor` part is all formatted.

**Pull request merged**
